### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by simosillankorva**
Work in progress. Some things currently missing: Proper include paths for header files. Tests for timer stuff. Test_M2MConnectionHandlerPimpl_classic needs to be added as fried class to M2MSecurity (this will need another pull request).

### CODE REVIEW

**Comment by anttiylitokola** [comment]
LGTM

**Comment by simosillankorva** [comment]
rebuild

**Comment by simosillankorva** [comment]
rebuild

**Comment by simosillankorva** [comment]
rebuild

**Pull request merged**
