### PR TITLE
connectionhandler: remove unnecessary include dependency on mbedos

### PR DESCRIPTION
**Pull request by TeroJaasko**
The code used mbed.h to get declaration of malloc() and free().
Replace that with platfom independent stdlib.h.

### CODE REVIEW

**Comment by jankii01** [comment]
Looks good to me! Quickly done Tero, thanks!

**Comment by jankii01** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by teetak01** [comment]
cloud-tests are ok, retriggered the other set.

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
Need to start pushing these PRs in now, builds are passing, Smoke runs are getting interrupted by CI. But this PR is good-to-go.

**Pull request merged**
