### PR TITLE
Change the connectionhandlerpimpl to use PAL.

### PR DESCRIPTION
**Pull request by simosillankorva**

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by teetak01** [comment]
Should all the dependencies (pal .libs) also be part of the PR or how are those going to be resolved?

**Comment by yogpan01** [comment]
-1 , This commit doesnt work in mbed Cloud Client with Bootstrap sequence, needs to be worked before merge can happen.
@teetak01 @simosillankorva

**Comment by teetak01** [comment]
rebuild

**Pull request merged**
